Repository gdgchennai/devfest2022-web, pull requests merged in 2022-10, with the labels that each got.

#49 Update images for memories from 2019 DevFest
  src/lib/section/memories/Memories.svelte
  static/memories_1.jpeg
  static/memories_2.jpeg
  static/memories_3.jpeg
  static/memories_4.jpeg
  static/memories_5.jpeg
  static/memories_6.jpeg
  static/memories_7.jpeg
  static/memories_8.jpeg
  static/memories_9.jpeg
Labels: enhancement, Change request

#50 Speaker cards: Fix padding in mobile view
  src/lib/section/speaker/speaker-card.svelte
  src/lib/section/speaker/speaker.svelte
Labels: bug

#51 FAQ: Add some additional content from devfest jalandhar
  src/lib/section/faq/FAQ.svelte
Labels: documentation

#54 Content: Update page wide content
  src/lib/footer/Footer.svelte
  src/lib/section/memories/Memories.svelte
  src/lib/section/tickets/Tickets.svelte
Labels: documentation, enhancement

#55 Feature: Add custom cursor effect style
  src/app.css
  src/routes/+page.svelte
Labels: enhancement, Feature

#56 UI: Do not affect hero with Y-paddings
  src/routes/+page.svelte
Labels: bug, enhancement

#57 Page: Do some alignment fixes
  src/lib/section/newsletter/Newsletter.svelte
  src/routes/+page.svelte
Labels: bug, enhancement

#58 Remove newsletter section
  src/lib/header/Header.svelte
  src/lib/section/newsletter/Newsletter.svelte
  src/routes/+page.svelte
Labels: Change request

#52 Modal popup for registration
  package-lock.json
  package.json
  src/lib/header/Header.svelte
  src/lib/modal/Modal.svelte
  src/lib/section/hero/Hero.svelte
  src/lib/section/tickets/Tickets.svelte
  src/routes/+layout.svelte
Labels: enhancement, Feature

#59 Made changes in website content
  src/lib/section/faq/FAQ.svelte
  src/lib/section/hero/Hero.svelte
  src/lib/section/memories/Memories.svelte
  src/lib/section/speaker/speaker.svelte
  src/lib/section/tickets/Tickets.svelte
  src/lib/section/why/Why.svelte
Labels: enhancement

#64 Bring back partner/sponsors section
  src/routes/+page.svelte
Labels: Change request

#69 Refactor ticket title to invite only
  src/lib/header/Header.svelte
  src/lib/section/hero/Hero.svelte
  src/lib/section/tickets/Tickets.svelte
Labels: Change request

#71 Hero: Add venue to calendar hyperlink
  src/lib/section/hero/Hero.svelte
Labels: enhancement, Change request

#74 Updates to badges feature
  src/lib/imageupload/ImageUpload.svelte
  src/routes/badges/+page.svelte
  static/attendee-circle.png
  static/attendee.png
  static/frame-attendee-circle.png
  static/frame-attendee.png
  static/frame-organizer-circle.png
  static/frame-organizer.png
  static/frame-speaker-circle.png
  static/frame-speaker.png
Labels: enhancement, Feature

#77 Badges improvements
  src/lib/imageupload/ImageUpload.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/badges/+page.svelte
Labels: bug, enhancement

#78 Speakers: Close CFP
  src/lib/section/speaker/speaker.svelte
Labels: Change request

#79 Header: Add badges to header navbar
  src/lib/header/Header.svelte
Labels: Change request

#80 Added assets, routes. Updated home page to add sponsorship info
  src/lib/section/partners/Partners.svelte
  src/lib/section/sponsors/Sponsors.svelte
  src/routes/+page.svelte
  src/routes/sponsorship/+page.svelte
  static/gdg-cloud-chennai.svg
  static/sponsorship.pdf
Labels: enhancement, Feature
