Repository gdgchennai/devfest2022-web, pull requests merged in 2022-09, with the labels that each got.

#18 Svelte landing page
  gdgchennai2022/.eslintignore
  gdgchennai2022/.eslintrc.cjs
  gdgchennai2022/.gitignore
  gdgchennai2022/.npmrc
  gdgchennai2022/.prettierignore
  gdgchennai2022/.prettierrc
  gdgchennai2022/README.md
  gdgchennai2022/package-lock.json
  gdgchennai2022/package.json
  gdgchennai2022/playwright.config.ts
  gdgchennai2022/postcss.config.cjs
  gdgchennai2022/src/app.css
  gdgchennai2022/src/app.d.ts
  gdgchennai2022/src/app.html
  gdgchennai2022/src/hooks.server.ts
  gdgchennai2022/src/routes/+layout.svelte
  gdgchennai2022/src/routes/+page.server.ts
  gdgchennai2022/src/routes/+page.svelte
  gdgchennai2022/src/routes/+page.ts
  gdgchennai2022/static/devfest-chennai.png
  gdgchennai2022/static/favicon.png
  gdgchennai2022/static/noise-grain.png
  gdgchennai2022/static/robots.txt
  gdgchennai2022/static/svelte-welcome.png
  gdgchennai2022/static/svelte-welcome.webp
  gdgchennai2022/svelte.config.js
  gdgchennai2022/tailwind.config.cjs
  gdgchennai2022/tests/test.ts
  gdgchennai2022/tsconfig.json
  gdgchennai2022/vite.config.ts
  package-lock.json
  package.json
  playwright.config.ts
  postcss.config.cjs
  src/app.css
  src/app.d.ts
  src/app.html
  src/hooks.server.ts
  src/routes/+layout.svelte
  src/routes/+page.server.ts
  src/routes/+page.svelte
  src/routes/+page.ts
  static/devfest-chennai.png
  static/favicon.png
  static/noise-grain.png
  static/robots.txt
  static/svelte-welcome.png
  static/svelte-welcome.webp
  svelte.config.js
  tailwind.config.cjs
  tests/test.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#19 refactor(Refactor code): :recycle: Clean up code and break everying i…
  .prettierrc
  .vscode/settings.json
  gdgchennai2022/.eslintignore
  gdgchennai2022/.eslintrc.cjs
  gdgchennai2022/.gitignore
  gdgchennai2022/.npmrc
  gdgchennai2022/.prettierignore
  gdgchennai2022/.prettierrc
  gdgchennai2022/README.md
  gdgchennai2022/package-lock.json
  gdgchennai2022/package.json
  gdgchennai2022/playwright.config.ts
  gdgchennai2022/postcss.config.cjs
  gdgchennai2022/src/app.css
  gdgchennai2022/src/app.d.ts
  gdgchennai2022/src/app.html
  gdgchennai2022/src/hooks.server.ts
  gdgchennai2022/src/routes/+layout.svelte
  gdgchennai2022/src/routes/+page.server.ts
  gdgchennai2022/src/routes/+page.svelte
  gdgchennai2022/src/routes/+page.ts
  gdgchennai2022/static/devfest-chennai.png
  gdgchennai2022/static/favicon.png
  gdgchennai2022/static/noise-grain.png
  gdgchennai2022/static/robots.txt
  gdgchennai2022/static/svelte-welcome.png
  gdgchennai2022/static/svelte-welcome.webp
  gdgchennai2022/svelte.config.js
  gdgchennai2022/tailwind.config.cjs
  gdgchennai2022/tests/test.ts
  gdgchennai2022/tsconfig.json
  gdgchennai2022/vite.config.ts
  src/routes/+page.server.ts
  src/routes/+page.svelte
Labels: enhancement

#25 build(Deployment): :rocket: Add node version for cloudflare deployment
  .node-version
  .vscode/settings.json
  package-lock.json
  package.json
Labels: bug

#26 feat(Components): :lipstick: Add core components
  .gitignore
  .vscode/settings.json
  src/lib/button/Button.svelte
  src/lib/footer/Footer.svelte
  src/lib/header/Header.svelte
  src/lib/header/svelte-logo.svg
  src/lib/icon/Icon.svelte
  src/lib/section/blur/Blur.svelte
  src/lib/section/hero/Hero.svelte
  src/lib/section/memories/Memories.svelte
  src/lib/section/newsletter/Newsletter.svelte
  src/lib/section/partners/Partners.svelte
  src/lib/section/tickets/Tickets.svelte
  src/lib/section/why/Why.svelte
  src/lib/types/Menu.ts
Labels: enhancement

#27 Add hero animation
  .vscode/settings.json
  src/lib/footer/Footer.svelte
  src/lib/header/Header.svelte
  src/lib/section/blur/Blur.svelte
  src/routes/+page.svelte
  tailwind.config.cjs
Labels: enhancement

#35 feat(Components): :sparkles: Add FAQ section
  src/lib/icon/Icon.svelte
  src/lib/section/faq/FAQ.svelte
  src/routes/+page.svelte
Labels: Feature

#36 Add newsletter item on bottom header
  src/lib/header/Header.svelte
  src/lib/icon/Icon.svelte
Labels: Feature

#42 Ticket price removal
  src/lib/section/tickets/Tickets.svelte
  src/static/devfest-chennai.png
  src/static/favicon.png
  src/static/robots.txt
Labels: documentation, enhancement

#43 Bring in Speaker section with dynamic speaker cards
  src/lib/section/speaker/speaker-card.svelte
  src/lib/section/speaker/speaker.svelte
  src/lib/section/tickets/Tickets.svelte
  src/routes/+page.svelte
  static/speaker-avatar.png
Labels: enhancement, Feature

#44 Update CFP link for speakers
  src/lib/section/speaker/speaker.svelte
Labels: enhancement

#45 Hero: Background orb - Relax animation
  src/lib/section/blur/Blur.svelte
Labels: enhancement

#46 Hide sponsors and assign speakers to nav menu
  src/lib/header/Header.svelte
  src/routes/+page.svelte
Labels: Change request

#47 FAQ: Add background and make it match the length of container
  src/lib/section/faq/FAQ.svelte
Labels: enhancement
